In [28]:
import numpy as np
import pandas as pd

In [29]:

df = pd.DataFrame([[8, 8, 4], [7, 9, 5], [6, 10, 6], [5, 12, 7]], columns=['cgpa', 'profile_score', 'lpa'])

In [30]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [31]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from tensorflow.keras.layers import Dense

In [32]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim =2))
model.add(Dense(1,activation='linear'))

C:\Users\HP TECHNOLOGY\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [33]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
model.get_weights()

[array([[ 1.0912985 , -0.32852292],
        [-0.85707825,  1.1908444 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.5700503],
        [ 0.744491 ]], dtype=float32),
 array([0.], dtype=float32)]

In [35]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]

In [36]:
new_weights

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [37]:
model.set_weights(new_weights)

In [38]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [39]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 23.5692  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 33.8785 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24.8205 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - loss: 26.4761
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 21.7344 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 31.8015 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 28.9264 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - loss: 26.2132
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 30.0613 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 24.2383 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 27.8846 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 18.3341 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 27.0834 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 701us/step - loss: 25.8576
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 25.5045 
Epoch 16/75
4/4

In [40]:
model.get_weights()

[array([[0.37375864, 0.37375864],
        [0.3659072 , 0.3659072 ]], dtype=float32),
 array([0.27253306, 0.27253306], dtype=float32),
 array([[0.37314907],
        [0.37314907]], dtype=float32),
 array([0.20490254], dtype=float32)]