In [15]:
import numpy as np
import pandas as pd

In [16]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [17]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [18]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model = Sequential()
model.add(Dense(2,activation='sigmoid',input_dim =2))
model.add(Dense(1,activation='sigmoid'))

C:\Users\HP TECHNOLOGY\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [20]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.get_weights()

[array([[-0.02963209,  0.76089895],
        [-0.350407  ,  0.6251601 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.63817585],
        [1.3116416 ]], dtype=float32),
 array([0.], dtype=float32)]

In [22]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]

In [23]:
new_weights

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [24]:
model.set_weights(new_weights)

In [25]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [26]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.6832  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6827 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6733 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6733 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.7327 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6827 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6838 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - loss: 0.6828
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.7164 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.7291 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6740 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6829 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.7287 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.7058 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - loss: 0.6585
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━

In [27]:
model.get_weights()

[array([[0.10275275, 0.10275275],
        [0.08106451, 0.08106451]], dtype=float32),
 array([-0.04401083, -0.04401083], dtype=float32),
 array([[0.08953476],
        [0.08953476]], dtype=float32),
 array([-0.02001895], dtype=float32)]